# Site settings
title: Mathistic
tagline: "Mathematics and Arts!"
description: "Articles about math, painting and anything in-between."
url: "http://laerne.github.io"
username: laerne

author:
    name: "Nicolas Brack"

#display settings
paginate: 12
paginate_path: "page-:num"
icon:
    small: public/icon32.png
    large: public/icon512.png

# Build settings
markdown: kramdown
highlighter: pygments
permalink: "/:year/:month/:day/:title/"


